In [1]:
# pip install opencv-python

In [3]:
import cv2
import numpy as np
import warnings 
warnings.simplefilter('ignore')

# load and read image

In [6]:
# load on the image using 'imread' specifying the path to image

img= cv2.imread('karthikbw.jpg',1)

##  lets take a closer look at how images are stored

In [7]:
print(img)

[[[134 134 134]
  [134 134 134]
  [134 134 134]
  ...
  [134 134 134]
  [134 134 134]
  [134 134 134]]

 [[134 134 134]
  [134 134 134]
  [134 134 134]
  ...
  [134 134 134]
  [134 134 134]
  [134 134 134]]

 [[134 134 134]
  [134 134 134]
  [134 134 134]
  ...
  [134 134 134]
  [134 134 134]
  [134 134 134]]

 ...

 [[254 254 254]
  [254 254 254]
  [254 254 254]
  ...
  [186 186 186]
  [151 151 151]
  [124 124 124]]

 [[254 254 254]
  [254 254 254]
  [254 254 254]
  ...
  [183 183 183]
  [151 151 151]
  [127 127 127]]

 [[254 254 254]
  [254 254 254]
  [254 254 254]
  ...
  [180 180 180]
  [150 150 150]
  [129 129 129]]]


# shape give the dimension of the image array

In [8]:
img.shape

# the 3d dimensions are 1358 pixel in height * 1500 pixel wide
# 3 means that there are 3 RGB that makeup this image

(750, 675, 3)

# display the image

In [9]:
# to display our image variable , we use imshow

cv2.imshow('pm', img)


# waitKey allow us to input information when a image window is open
cv2.waitKey()

# cv2.waitKey(2000) (time in milisecond)

# this close all open window
# failure to place this will cause your program to hang
cv2.destroyAllWindows()

In [17]:
img= cv2.imread('Modi.jpg')
cv2.imshow('pm', img)
cv2.waitKey()
cv2.destroyAllWindows()

# save the image

In [18]:
# 
cv2.imwrite('Modi.jpg', img)

True

# resize the image

In [20]:
img= cv2.imread('modi.jpg')

resize = cv2.resize(img,(500,500))

grey = cv2.cvtColor(resize, cv2.COLOR_BGR2GRAY)

cv2.imshow('modi image', grey)

cv2.waitKey()

cv2.destroyAllWindows()

In [21]:
img.shape[0]*0.5

679.0

In [22]:
img.shape[1]*0.5

750.0

# face Detection Using HAAR Cascade Classifiers

In [28]:
 # we point Open cv cascade classifier function to where our classifier 
face_classifier = cv2.CascadeClassifier('Haarcascades\\haarcascade_frontalface_default.xml')

# load our image and convert it to grayscale

img= cv2.imread('modi.jpg')
img = cv2.resize(img,(500,500))
grey = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# turning cascade classifier - detectMultiScale ( input image , scaler factor , min neighbors)
faces = face_classifier.detectMultiScale(grey, 1.05,5)

In [29]:
print(faces)

[[205  80 216 216]]


In [31]:
face_classifier = cv2.CascadeClassifier('Haarcascades\\haarcascade_frontalface_default.xml')

# load our image and convert it to grayscale

img= cv2.imread('Modi.jpg')
img = cv2.resize(img,(500,500))
grey = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# turning cascade classifier - detectMultiScale ( input image , scaler factor , min neighbors)
faces = face_classifier.detectMultiScale(grey, 1.05,5)

# when no faces detected , face classifier returns and empty tuple 

if faces is ():
    print('no face found')
# we iterate through our faces array and draw rectangle
# over each face in faces

for (x,y,w,h) in faces:
    cv2.rectangle(img, (x,y), (x+w,y+h), (0,255,100),1)
    
cv2.imshow('face detection', img)
cv2.waitKey()
cv2.destroyAllWindow()
    

AttributeError: module 'cv2' has no attribute 'destroyAllWindow'

# face & eye detection 

In [14]:
face_classifier = cv2.CascadeClassifier('D:\\self study\\Naresh IT\\Data Science\\24. Computer Vision\\Haarcascades\\haarcascade_frontalface_default.xml')
eye_classifier = cv2.CascadeClassifier('D:\\self study\\Naresh IT\\Data Science\\24. Computer Vision\\Haarcascades\\haarcascade_eye.xml')


img= cv2.imread('D:\\self study\\Naresh IT\\Data Science\\24. Computer Vision\\image_examples\\modi.jpg')
img = cv2.resize(img,(500,500))
grey = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
faces = face_classifier.detectMultiScale(grey, 1.03,5)

# when no faces detected , face classifier returns and empty tuple 

if faces is ():
    print('no face found')

for (x,y,w,h) in faces:
    cv2.rectangle(img, (x,y), (x+w,y+h), (0,255,100),2)
    roi_grey = grey[y:y+h, x:x+w]
    roi_color = img[y:y+h, x:x+w]
    eyes = eye_classifier.detectMultiScale(roi_grey)
    
    for (ex,ey,ew,eh) in eyes:
        cv2.rectangle(roi_color, (ex,ey), (ex+ew,ey+eh),(0,255,0),2)

    
cv2.imshow('face ', img)
cv2.waitKey()
cv2.destroyAllWindow()


AttributeError: module 'cv2' has no attribute 'destroyAllWindow'

 # Capture a vedio

In [1]:
# doing some face recognigation with the webcam

import cv2
vedio =  cv2.VideoCapture(0) # 0--webcam

while True:
    check,frame = vedio.read()
    gray = cv2.cvtColor(frame , cv2.COLOR_BGR2GRAY)
    cv2.imshow('vedio', frame)
    if cv2.waitKey(1)==ord('q'):
        break
        
        
video.release()
cv2.destroyAllWindows()

NameError: name 'video' is not defined

# face & eye detection cascade classifiers

In [1]:

import cv2
face_classifier = cv2.CascadeClassifier('D:\\self study\\Naresh IT\\Data Science\\24. Computer Vision\\Haarcascades\\haarcascade_frontalface_default.xml')
eye_classifier = cv2.CascadeClassifier('D:\\self study\\Naresh IT\\Data Science\\24. Computer Vision\\Haarcascades\\haarcascade_eye.xml')

def detect( grey, frame):
    faces = face_cascade.detectMultiScale(gray,1.3,5)
    for (x,y,w,h) in faces:
        cv2.rectangle(frame, (x,y),(x+w,y+h), (255,0,0),2)
        roi_grey = grey[y:y+h, x:x+w]
        roi_color = img[y:y+h, x:x+w]
        eyes = eye_classifier.detectMultiScale(roi_grey, 1.1,3)
        
        for (ex,ey,ew,eh) in eyes:
            cv2.rectangle(roi_color, (ex,ey), (ex+ew,ey+eh),(0,255,0),2)
    return frame

# doing some face recognition with the webcam

vedio = cv2.VideoCapture(0)

while True:
    check,frame = vedio.read()
    gray = cv2.cvtColor(frame , cv2.COLOR_BGR2GRAY)
    cv2.imshow('vedio', gray)
    canvas = detect(grey,frame)
    
    cv2.imshow('vedio', canvas)
    if cv2.waitKey(1)==ord('q'):
        break
        
        
video.release()
cv2.destroyAllWindows()        

NameError: name 'grey' is not defined

 # pedistrian detection

In [4]:
import cv2
# create our body classifier
body_classifier = cv2.CascadeClassifier('D:\\self study\\Naresh IT\\Data Science\\24. Computer Vision\\Haarcascades\\haarcascade_fullbody.xml')

# initiate video capture for video file

cap = cv2.VideoCapture('D:\\self study\\Naresh IT\\Data Science\\24. Computer Vision\\image_example\\walking.avi')

# loop once video is successfully loaded

while cap.isOpened():
    
    # read first frame
    check,frame = cap.read()
    gray = cv2.cvtColor(frame , cv2.COLOR_BGR2GRAY) 
    # pass frame to our body classifier
    
    bodies = body_classifier.detectMultiScale(grey,1.2,3)
    
    # extract bounding boxes for any bodies
    
    for (x,y,w,h) in bodies:
        cv2.rectangle(frame, (x,y),(x+w,y+h), (255,0,0),2)
        cv2.imshow('pedestrian', frame)
    
    
    if cv2.waitKey(1)==ord('q'):
        break
        
        
cap.release()
cv2.destroyAllWindows() 
    

In [ ]:
import time

