**OpenCV installation can be done in two ways**
- Conda install - c conda - forge opencv
- pip install opencv - python

In [1]:
#pip install opencv-python

In [1]:
import cv2
import numpy as np
import warnings
warnings.simplefilter("ignore")

In [37]:
print(cv2.__version__)

4.12.0


# Load / Read images
**Load an image using "imread" specifying the path to image**

In [38]:
pwd

'C:\\Users\\gorap\\Data science\\AI\\Computer Vision'

In [39]:
img = cv2.imread("image_examples\\Modi.jpg",1)

In [40]:
cv2.imshow("prime minister",img)
cv2.waitKey() == ord("q")
cv2.destroyAllWindows()

**Lets take a close look at how images are stored**

In [41]:
img

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

In [42]:
img.shape  #(y,x),(height ,width)

(1358, 1500, 3)

In [43]:
img.ndim

3

**Resize Image**

In [44]:
img = cv2.imread("image_examples\\karthik.jpg",0)# Load the image directy to gray scale
resized_img = cv2.resize(img,(675,750))
cv2.imshow("PM",resized_img)
cv2.waitKey() == ord("q")
cv2.destroyAllWindows()

In [45]:
print(chr(113)) ## ASCII (or Unicode) integer code.

q


In [46]:
img = cv2.imread("image_examples\\karthik.jpg",1)
resized_img = cv2.resize(img,(675,750))
gray = cv2.cvtColor(resized_img,cv2.COLOR_BGR2GRAY) # Convert color to grey scale
cv2.imshow("PM",gray)
cv2.waitKey() == ord("q")
cv2.destroyAllWindows()

# Save the image 
**Simply we "imwrite" specifically the file name and image to be saved**

In [47]:
cv2.imwrite("karthikbw.jpg",gray)

True

# Computer Vision
- Object  detection as per your requirement
- Ex : if you want to detect mobile.humna face, with in given image 

# Face Detection using HAAR Cascade Classifier 

In [48]:
# loass the features
face_classifier = cv2.CascadeClassifier("C:\\Users\\gorap\\Data science\\AI\\Computer Vision\\Haarcascades\\haarcascade_frontalface_default.xml")

# apply for on what you want to check
image = cv2.imread("image_examples\\Modi.jpg",1)
image = cv2.resize(image,(679,750))
gray = cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)
# matching the features on the guven image
faces = face_classifier.detectMultiScale(gray, 1.05,5)

if faces is ():
    print("No face found")
# we iterate through our faces array and draw rectangle
# over each face in faces
else :
    for (x,y,l,h) in faces :
        cv2.rectangle(image,(x,y),(x+l,y+h),(0,255,0),2)
        
cv2.imshow("Face Detected", image)
cv2.waitKey() == ord("q")
cv2.destroyAllWindows()

In [49]:
faces

array([[276, 128, 301, 301]], dtype=int32)

In [50]:
face_classifier = cv2.CascadeClassifier("C:\\Users\\gorap\\Data science\\AI\\Computer Vision\\Haarcascades\\haarcascade_frontalface_default.xml")
image = cv2.imread("image_examples\\karthik.jpg",1)
image = cv2.resize(image,(500,600))
faces = face_classifier.detectMultiScale(image,1.05,5)
if faces is ():
    print("Face is not detected")
else :
    for (x,y,l,h) in faces:
        cv2.rectangle(image,(x,y),(x+l,y+h),(0,255,255),2)
cv2.imshow("karthik",image)
cv2.waitKey() == ord("q")
cv2.destroyAllWindows()


In [51]:
print("Persons in the image : ",faces.shape[0])

Persons in the image :  1


In [52]:
face_classifier = cv2.CascadeClassifier("C:\\Users\\gorap\\Data science\\AI\\Computer Vision\\Haarcascades\\haarcascade_frontalface_default.xml")
image = cv2.imread("image_examples\\manam.jpg",1)
image = cv2.resize(image,(500,600))
faces = face_classifier.detectMultiScale(image,1.1,5)
if faces is ():
    print("Face is not detected")
else :
    for (x,y,l,h) in faces:
        cv2.rectangle(image,(x,y),(x+l,y+h),(0,255,255),2)
cv2.imshow("karthik",image)
cv2.waitKey() == ord("q")
cv2.destroyAllWindows()


In [53]:
print("Persons in the image : ",faces.shape[0])

Persons in the image :  4


In [54]:
face_classifier = cv2.CascadeClassifier("C:\\Users\\gorap\\Data science\\AI\\Computer Vision\\Haarcascades\\haarcascade_frontalface_default.xml")
image = cv2.imread("image_examples\\boyes.jpg",1)
image = cv2.resize(image,(600,400))
faces = face_classifier.detectMultiScale(image,1.05,5)
if faces is ():
    print("Face is not detected")
else :
    for (x,y,l,h) in faces:
        cv2.rectangle(image,(x,y),(x+l,y+h),(0,255,255),2)
cv2.imshow("karthik",image)
cv2.waitKey() == ord("q")
cv2.destroyAllWindows()


In [55]:
print("Persons in the image : ",faces.shape[0])

Persons in the image :  14


# Eye Detection using HAAR Cascade Classifier 

In [56]:
eye_classifier = cv2.CascadeClassifier("C:\\Users\\gorap\\Data science\\AI\\Computer Vision\\Haarcascades\\haarcascade_eye.xml")
image = cv2.imread("image_examples\\Modi.jpg",1)
image = cv2.resize(image,(500,500))
eyes = eye_classifier.detectMultiScale(image,1.05,5)
if eyes is ():
    print("eyes is not detected")
else :
    for (x,y,l,h) in eyes:
        cv2.rectangle(image,(x,y),(x+l,y+h),(0,255,255),2)
cv2.imshow("karthik",image)
cv2.waitKey() == ord("q")
cv2.destroyAllWindows()

In [57]:
eye_classifier = cv2.CascadeClassifier("C:\\Users\\gorap\\Data science\\AI\\Computer Vision\\Haarcascades\\haarcascade_eye.xml")
image = cv2.imread("image_examples\\manam.jpg",1)
image = cv2.resize(image,(500,500))
eyes = eye_classifier.detectMultiScale(image,1.2,5)
if eyes is ():
    print("eyes is not detected")
else :
    for (x,y,l,h) in eyes:
        cv2.rectangle(image,(x,y),(x+l,y+h),(0,255,255),2)
cv2.imshow("karthik",image)
cv2.waitKey() == ord("q")
cv2.destroyAllWindows()

# Face and Eye detection using HAArCascade Classifier

In [58]:
# loass the features
face_classifier = cv2.CascadeClassifier("C:\\Users\\gorap\\Data science\\AI\\Computer Vision\\Haarcascades\\haarcascade_frontalface_default.xml")
eye_classifier = cv2.CascadeClassifier("C:\\Users\\gorap\\Data science\\AI\\Computer Vision\\Haarcascades\\haarcascade_eye.xml")
# load the image 
image = cv2.imread("image_examples\\karthik.jpg")
image = cv2.resize(image,(500,500))
gray = cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)
faces = face_classifier.detectMultiScale(image,1.05,5)
if faces is ():
    print("NO face is forund")
else:
    for (x,y,l,h) in faces :
        cv2.rectangle(image,(x,y),(x+l,y+h),(0,255,255),2)
        face_rectangle_color = image[y:y+h,x:x+l]
        face_rectangle_BW = gray[y:y+h,x:x+l]
        eyes = eye_classifier.detectMultiScale(face_rectangle_color,1.2,5)
        for (ex,ey,el,eh) in eyes:
            cv2.rectangle(face_rectangle_color,(ex,ey),(ex+el,ey+eh),(0,255,0),2)
cv2.imshow("PM",image)
cv2.waitKey()
cv2.destroyAllWindows()

In [59]:
# loass the features
face_classifier = cv2.CascadeClassifier("C:\\Users\\gorap\\Data science\\AI\\Computer Vision\\Haarcascades\\haarcascade_frontalface_default.xml")
eye_classifier = cv2.CascadeClassifier("C:\\Users\\gorap\\Data science\\AI\\Computer Vision\\Haarcascades\\haarcascade_eye.xml")
# load the image 
image = cv2.imread("image_examples\\Modi.jpg")
image = cv2.resize(image,(500,500))
gray = cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)
faces = face_classifier.detectMultiScale(image,1.35,5)
if faces is ():
    print("NO face is forund")
else:
    for (x,y,l,h) in faces :
        cv2.rectangle(gray,(x,y),(x+l,y+h),(0,255,255),2)
        face_rectangle_color = image[y:y+h,x:x+l]
        face_rectangle_BW = gray[y:y+h,x:x+l]
        eyes = eye_classifier.detectMultiScale(face_rectangle_BW,1.01,5)
        for (ex,ey,el,eh) in eyes:
            cv2.rectangle(face_rectangle_BW,(ex,ey),(ex+el,ey+eh),(0,255,0),2)
cv2.imshow("PM",gray)
cv2.waitKey()
cv2.destroyAllWindows()

In [60]:
faces

array([[208,  83, 210, 210]], dtype=int32)

# Capturing Videos

In [61]:
# doing some face recognision eith web cam
import cv2
video = cv2.VideoCapture(0)  #-- 0(web cam)
while True :
    num,frame = video.read()
    #gray = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    cv2.imshow("video",gray)
    if cv2.waitKey(1) == ord("q"):
        break
video.release()
cv2.destroyAllWindows()

## Face and eye Detection using HAAR Cascade Classifier in videos 

In [4]:
# load the features
face_classifier = cv2.CascadeClassifier("C:\\Users\\gorap\\Data science\\AI\\Computer Vision\\Haarcascades\\haarcascade_frontalface_default.xml")
eye_classifier = cv2.CascadeClassifier("C:\\Users\\gorap\\Data science\\AI\\Computer Vision\\Haarcascades\\haarcascade_eye.xml")
def detect (gray,frame):
    faces = face_classifier.detectMultiScale(gray,1.05,5)
    for (x,y,l,h) in faces :
        cv2.rectangle(frame,(x,y),(x+l,y+h),(255,0,0),2)
        face_rectangle_color = frame[y:y+h,x:x+l]
        face_rectangle_BW = gray[y:y+h,x:x+l]
        eyes = eye_classifier.detectMultiScale(face_rectangle_BW,1.05,5)
        for (ex,ey,el,eh) in eyes:
            cv2.rectangle(face_rectangle_color,(ex,ey),(ex+el,ey+eh),(0,255,0),2)

    return frame   

# doing face recognition with webcam
video = cv2.VideoCapture(0)
while True :
    num ,frame = video.read()
    gray = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    canvas = detect(gray,frame)
    cv2.imshow("video",canvas)
    if cv2.waitKey(1) == ord("q"):
        break
video.release()
cv2.destroyAllWindows()

In [5]:
# load the features
face_classifier = cv2.CascadeClassifier("C:\\Users\\gorap\\Data science\\AI\\Computer Vision\\Haarcascades\\haarcascade_frontalface_default.xml")
eye_classifier = cv2.CascadeClassifier("C:\\Users\\gorap\\Data science\\AI\\Computer Vision\\Haarcascades\\haarcascade_eye.xml")
def detect (gray,frame):
    faces = face_classifier.detectMultiScale(gray,1.05,5)
    for (x,y,l,h) in faces :
        cv2.rectangle(frame,(x,y),(x+l,y+h),(255,0,0),2)
        face_rectangle_color = frame[y:y+h,x:x+l]
        face_rectangle_BW = gray[y:y+h,x:x+l]
        eyes = eye_classifier.detectMultiScale(face_rectangle_BW,1.05,5)
        for (ex,ey,el,eh) in eyes:
            cv2.rectangle(face_rectangle_color,(ex,ey),(ex+el,ey+eh),(0,255,0),2)

    return frame   

# doing face recognition with webcam
video = cv2.VideoCapture(0)
while True :
    num ,frame = video.read()
    gray = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    canvas = detect(gray,gray)
    cv2.imshow("video",canvas)
    if cv2.waitKey(1) == ord("q"):
        break
video.release()
cv2.destroyAllWindows()

## Pedistrian Detection 

In [74]:
import cv2
import numpy as np
import warnings
warnings.simplefilter("ignore")

In [75]:
# load the features
import time 
body_classifier = cv2.CascadeClassifier("C:\\Users\\gorap\\Data science\\AI\\Computer Vision\\Haarcascades\\haarcascade_fullbody.xml")
# 
cap = cv2.VideoCapture("image_examples\\Walking.avi")
# detect
while cap.isOpened():
    time.sleep(0.01)
    num,frame = cap.read()
    gray = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    bodies = body_classifier.detectMultiScale(gray,1.1,3)

    for  (x,y,l,h) in bodies :
        cv2.rectangle(frame,(x,y),(x+l,y+h),(255,0,255),2)
        cv2.imshow("persons",frame)
    if cv2.waitKey(1) == ord("q"):
        break
cap.release()
cv2.destroyAllWindows()

# Car  detection

In [ ]:
# load the features
import time 
cars_classifier = cv2.CascadeClassifier("C:\\Users\\gorap\\Data science\\AI\\Computer Vision\\Haarcascades\\haarcascade_car.xml")
# 
cap = cv2.VideoCapture("image_examples\\cars.avi")
# detect
while cap.isOpened():
    time.sleep(0.01)
    num,frame = cap.read()
    gray = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    cars = cars_classifier.detectMultiScale(gray,1.01,5)

    for  (x,y,l,h) in cars :
        cv2.rectangle(frame,(x,y),(x+l,y+h),(255,0,255),2)
        cv2.imshow("cars",frame)
    if cv2.waitKey(1) == ord("q"):
        break
cap.release()
cv2.destroyAllWindows()